apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-service
spec:
  hosts:
    - redis-service
  http:
    - route:
        - destination:
            host: redis-service
            subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: userapi-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - userapi-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: userapi-service
        port:
          number: 3001
        subset: v2